from typing import Protocol

from megabone.qt import QGraphicsView, QPointF


class EditorControllerProtocol(Protocol):
    def handle_mouse_press(self, view: QGraphicsView, event) -> None: ...
    def handle_mouse_move(self, view: QGraphicsView, event) -> None: ...
    def handle_mouse_release(self, view: QGraphicsView, event) -> None: ...
    def on_sprite_dropped(self, path: str, index: int, scene_pos: QPointF) -> None: ...
