from typing import Protocol

from megabone.qt import QGraphicsView


class EditorControllerProtocol(Protocol):
    def handle_mouse_press(self, view: QGraphicsView, event) -> None: ...
    def handle_mouse_move(self, view: QGraphicsView, event) -> None: ...
    def handle_mouse_release(self, view: QGraphicsView, event) -> None: ...
